name: Build, Scan and Publish sfy-manifest-service

on:
  push:

env:
  TEST_ENV: ${{ vars.TEST_ENV }}


jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: echoing
        run: |
          echo ${{ env.TEST_ENV }}
