name: Build, Scan and Publish sfy-manifest-service

on:
  push:


jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          file: Dockerfile
          context: .
          platforms: linux/amd64 # arm intentionally excluded since we can do with just amd for scan image action
          tags: |
            quay.io/vedant99/test-s3:${{ steps.vars.outputs.sha_short }}
          cache-from: type=registry,ref=quay.io/vedant99/test-s3-buildcache
          cache-to: mode=max,image-manifest=true,type=registry,ref=quay.io/vedant99/test-s3-buildcache
